# Generated by Django 5.2.4 on 2025-07-09 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_meetingminuteentry_parent_task_task_parent_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminuteentry',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minute_entry', to='mainapp.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tasks', to='mainapp.task'),
        ),
    ]
